// import { ClusterProvider } from '@/components/cluster/cluster-data-access'
// import { SolanaProvider } from '@/components/solana/solana-provider'
// import { UiLayout } from '@/components/ui/ui-layout'
import { ReactQueryProvider } from '../react-query-provider'

import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'

export const metadata = {
  title: 'Incobs',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Incobs Program', path: '/incobs' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (

    <ClerkProvider>
      <ReactQueryProvider>
        {/* <ClusterProvider>
              <SolanaProvider> */}
        {/* <header className="flex justify-end items-center p-4 gap-4 h-16">
          <SignedOut>
            <SignInButton />
            <SignUpButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header> */}
        {children}
        {/* <UiLayout links={links}>{children}</UiLayout> */}
        {/* </SolanaProvider>
            </ClusterProvider> */}
      </ReactQueryProvider>
    </ClerkProvider>

  )
}
