import './globals.css'


export const metadata = {
    title: 'Incobs',
    description: 'Generated by create-solana-dapp',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}
