import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/providers";
import { Toaster } from "sonner";
import "@/lib/polyfills";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Dynamic App",
  description: "Generated by create dynamic app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>{children}</Providers>
        <Toaster
          position="top-center"
          richColors
        />
      </body>
    </html>
  );
}