[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
# mcbuse_wallets = "7V3amFUk7nFV2rt8ucrupRA3nGGEmGTu4CXqiVfFqt9U"
mcbuse_wallets = "E4eWGJX7rctj5NjhKvPHLDfEUcN8mkT29uVC8tGoLZCZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
